# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog du projet ift6266 -- Louis van Beurden
email: louis.vanbeurden@gmail.com
baseurl: "/ift6266" # the subpath of your site, e.g. /blog
url: "https://ogrergo.github.io/" # the base hostname & protocol for your site
github_username:  ogrergo

# Build settings
markdown: kramdown
theme: jekyll-theme-time-machine
