# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IFT6266 Blog
email: louis.vanbeurden@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Blog post on the advencement of my deep learning project for the course ift6266.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  ogrergo

# Build settings
markdown: kramdown
